# Import numpy

In [2]:
import numpy as np 

In [2]:
x = [1, 2, 3]

In [4]:
x

[1, 2, 3]

In [5]:
type(x)

list

In [6]:
y = np.array(x)

In [7]:
y

array([1, 2, 3])

In [8]:
z = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
a = np.arange(2, 100000, 3)
a

array([    2,     5,     8, ..., 99992, 99995, 99998])

In [8]:
a[100]

302

In [14]:
np.random.random((3,4))

array([[0.79183512, 0.09763591, 0.66894643, 0.78276588],
       [0.84407277, 0.32222653, 0.43912361, 0.30786648],
       [0.13942954, 0.99735218, 0.64617215, 0.74511261]])

In [18]:
a = np.random.randint(2, 10, 7)
a 

array([4, 8, 9, 2, 3, 7, 7])

In [19]:
a.max()

9

In [20]:
a.min()

2

In [21]:
a.mean()

5.714285714285714

In [22]:
a.sum()

40

In [23]:
a.std()

2.4907993963089563

In [24]:
a = np.random.randint(0, 100, (6,5))
a

array([[59, 97, 33, 65,  0],
       [58, 45, 24, 94, 37],
       [35, 54, 11,  5,  0],
       [83, 31, 44, 30, 30],
       [69, 18, 33, 74, 58],
       [44, 68, 21, 80, 28]])

In [25]:
a.max()

97

In [26]:
a.max(axis=0)

array([83, 97, 44, 94, 58])

In [27]:
a.max(axis=1)

array([97, 94, 54, 83, 74, 80])