# Import numpy

In [1]:
import numpy as np 

In [2]:
x = [1, 2, 3]

In [3]:
x

[1, 2, 3]

In [4]:
type(x)

list

In [5]:
y = np.array(x)

In [6]:
y

array([1, 2, 3])

In [7]:
z = np.array([[1, 2, 3], [4, 5, 6]])

In [8]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
a = np.arange(2, 100000, 3)
a

array([    2,     5,     8, ..., 99992, 99995, 99998])

In [11]:
a[100]

302

In [12]:
np.random.random((3,4))

array([[0.99252206, 0.9356919 , 0.51207071, 0.79177217],
       [0.1160936 , 0.40231098, 0.70554339, 0.84365194],
       [0.49917895, 0.07126907, 0.22789399, 0.90634183]])

In [13]:
a = np.random.randint(2, 10, 7)
a 

array([4, 6, 2, 8, 3, 3, 8])

In [14]:
a.max()

8

In [15]:
a.min()

2

In [16]:
a.mean()

4.857142857142857

In [17]:
a.sum()

34

In [18]:
a.std()

2.294625486315573

In [19]:
a = np.random.randint(0, 100, (6,5))
a

array([[70, 36, 90, 70, 34],
       [32, 70, 12, 56, 79],
       [61,  0, 28, 39, 12],
       [82, 96, 54, 57,  0],
       [40, 68, 95, 12, 78],
       [29, 47, 58,  3, 61]])

In [20]:
a.max()

96

In [21]:
a.max(axis=0)

array([82, 96, 95, 70, 79])

In [22]:
a.max(axis=1)

array([90, 79, 61, 96, 95, 61])

In [23]:
a

array([[70, 36, 90, 70, 34],
       [32, 70, 12, 56, 79],
       [61,  0, 28, 39, 12],
       [82, 96, 54, 57,  0],
       [40, 68, 95, 12, 78],
       [29, 47, 58,  3, 61]])

In [24]:
b = np.random.randint(0, 100, 7)
b

array([81, 60, 83, 80, 46,  9, 20])

In [25]:
len(b)

7

In [26]:
b[0]

81

In [27]:
b[1]

60

In [28]:
b[-1]

20

In [29]:
b[2:5]

array([83, 80, 46])

In [30]:
a

array([[70, 36, 90, 70, 34],
       [32, 70, 12, 56, 79],
       [61,  0, 28, 39, 12],
       [82, 96, 54, 57,  0],
       [40, 68, 95, 12, 78],
       [29, 47, 58,  3, 61]])

In [31]:
a[2][2]

28

In [32]:
a[4][4]

78

In [33]:
a[5][0]

29


# Array Shape number of rows & cols

In [34]:
a.shape

(6, 5)

In [35]:
a.ndim

2

In [36]:
a.size

30

In [37]:
a.shape[0]

6

In [38]:
a.shape[1]

5

In [62]:
r = np.random.randint(2000, 10000, 1000000, dtype=np.int64)
r

array([4489, 5639, 6381, ..., 2814, 7512, 6135], dtype=int64)

In [63]:
r.max()

9999

In [64]:
r.min()

2000

In [65]:
v = (4/3) * np.pi * np.power(r, 3)
v

array([3.78911185e+11, 7.51095038e+11, 1.08831557e+12, ...,
       9.33385153e+10, 1.77564175e+12, 9.67235684e+11])

In [66]:
v.max()

4187533693384.472

In [67]:
v.min()

33510321638.291122

In [68]:
np.array([1,2,3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

In [69]:
2 ** 7 

128

In [70]:
2 ** 8 

256

In [71]:
input().strip().split(' ')

['1', '13', '7', '6']

In [72]:
a

array([[70, 36, 90, 70, 34],
       [32, 70, 12, 56, 79],
       [61,  0, 28, 39, 12],
       [82, 96, 54, 57,  0],
       [40, 68, 95, 12, 78],
       [29, 47, 58,  3, 61]])

In [82]:
np.where(a<10, a+1, a-2)

array([[68, 34, 88, 68, 32],
       [30, 68, 10, 54, 77],
       [59,  1, 26, 37, 10],
       [80, 94, 52, 55,  1],
       [38, 66, 93, 10, 76],
       [27, 45, 56,  4, 59]])

In [75]:
b

array([81, 60, 83, 80, 46,  9, 20])

In [76]:
[x+1 for x in b]

[82, 61, 84, 81, 47, 10, 21]

In [79]:
[x+1 if x <10 else x for x in b ]

[81, 60, 83, 80, 46, 10, 20]

In [83]:
a

array([[70, 36, 90, 70, 34],
       [32, 70, 12, 56, 79],
       [61,  0, 28, 39, 12],
       [82, 96, 54, 57,  0],
       [40, 68, 95, 12, 78],
       [29, 47, 58,  3, 61]])

In [84]:
a.clip(10, 60)

array([[60, 36, 60, 60, 34],
       [32, 60, 12, 56, 60],
       [60, 10, 28, 39, 12],
       [60, 60, 54, 57, 10],
       [40, 60, 60, 12, 60],
       [29, 47, 58, 10, 60]])